
spring:
  datasource:
    druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off

#开启mp的日志（输出到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto
#      table-prefix: tbl_
server:
  port: 80
